spring:
  profiles:
    active: dev
  jackson:
    dateFormat: yyyy-MM-dd'T'HH:mm:ssZZ
    timeZone: UTC
  datasource:
    testOnBorrow: true
    validationQuery: SELECT 1
  jpa:
    show_sql: true
    format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  session:
    store-type: redis
    namespace: boilerplate
  redis:
    host: localhost
    port: 6379

server:
  port: 8080

management:
  health:
    db:
      enabled: true

logging:
  file: ./spring-boot-boilerplate.log
  level:
    com.exmertec: warn
