spring:
  datasource:
    url: jdbc:mysql://localhost:3309/spring-boot-boilerplate?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  session:
    store-type: redis
    redis:
      namespace: spring-boot-boilerplate
